numero1=float(input("Ingrese su primero numero:",))
numero2=float(input("Ingrese su segundo numero:",))
numero3=float(input("Ingrese su tercero numero:",))
mayor=max(numero1,numero2,numero3)
print("El numero mayor es:",mayor)